flip/config/routes.rb
Flip::Application.routes.draw do
  

  
  resources :goodies

  root :to => 'pages#index'
  get 'about' => 'pages#about'

  devise_for :users

  

end

flip/app/models/goody.rb
class Goody < ActiveRecord::Base
  attr_accessible :description
end

flip/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

flip/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

flip/app/controllers/goodies_controller.rb
class GoodiesController < ApplicationController
  # GET /goodies
  # GET /goodies.json
  def index
    @goodies = Goody.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @goodies }
    end
  end

  # GET /goodies/1
  # GET /goodies/1.json
  def show
    @goody = Goody.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @goody }
    end
  end

  # GET /goodies/new
  # GET /goodies/new.json
  def new
    @goody = Goody.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @goody }
    end
  end

  # GET /goodies/1/edit
  def edit
    @goody = Goody.find(params[:id])
  end

  # POST /goodies
  # POST /goodies.json
  def create
    @goody = Goody.new(params[:goody])

    respond_to do |format|
      if @goody.save
        format.html { redirect_to @goody, notice: 'Goody was successfully created.' }
        format.json { render json: @goody, status: :created, location: @goody }
      else
        format.html { render action: "new" }
        format.json { render json: @goody.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /goodies/1
  # PUT /goodies/1.json
  def update
    @goody = Goody.find(params[:id])

    respond_to do |format|
      if @goody.update_attributes(params[:goody])
        format.html { redirect_to @goody, notice: 'Goody was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @goody.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goodies/1
  # DELETE /goodies/1.json
  def destroy
    @goody = Goody.find(params[:id])
    @goody.destroy

    respond_to do |format|
      format.html { redirect_to goodies_url }
      format.json { head :no_content }
    end
  end
end

flip/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

flip/app/helpers/application_helper.rb
module ApplicationHelper
end

flip/app/helpers/goodies_helper.rb
module GoodiesHelper
end

flip/app/helpers/pages_helper.rb
module PagesHelper
end

flip/app/views/goodies/_form.html.erb
<%= simple_form_for(@goody) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

flip/app/views/goodies/edit.html.erb
<h1>Editing goody</h1>

<%= render 'form' %>

<%= link_to 'Show', @goody %> |
<%= link_to 'Back', goodies_path %>

flip/app/views/goodies/index.html.erb
<h1>Listing goodies</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @goodies.each do |goody| %>
  <tr>
    <td><%= goody.description %></td>
    <td><%= link_to 'Show', goody %></td>
    <td><%= link_to 'Edit', edit_goody_path(goody) %></td>
    <td><%= link_to 'Destroy', goody, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Goody', new_goody_path %>

flip/app/views/goodies/new.html.erb
<h1>New goody</h1>

<%= render 'form' %>

<%= link_to 'Back', goodies_path %>

flip/app/views/goodies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @goody.description %>
</p>


<%= link_to 'Edit', edit_goody_path(@goody) %> |
<%= link_to 'Back', goodies_path %>

flip/app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "AK", "Http://emailalice.com" %>
	</small>

	
</div>

flip/app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>


      <!-- Be sure to leave the brand out there if you want it shown -->
      <!--<a class="brand" href="#">I.D.A.T.</a> -->
      <% link_to "I.D.A.T.", root_path, class: "brand" %>

      	<div class="nav-collapse"> 
      		<ul class="nav">
      			<li>
  					<%= link_to 'Home', root_path %>
  				</li>
  				<li>
					<%= link_to 'About', about_path %>
				</li>
			</ul>
			<ul class="nav pull-right">
			<% if user_signed_in? %>
				
				<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
				<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
				<% else %>
				<li><%= link_to 'Login', '#' %></li>
				<% end %>
			</ul>
		</div>


      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
      </div>
 
    </div>
  </div>
</div>

flip/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>I Didn't Ask for This: Funny Images For Professionals</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
<%= yield %>

<%= render 'layouts/footer' %>
</div>

</body>
</html>

flip/app/views/pages/about.html.erb
<h1>About</h1>
<p>
This site is dedicated to people, animals, and non-breathing things that didn't ask this that.

</p>

flip/app/views/pages/index.html.erb
<div class="row">
<div class="span4">
<%= image_tag("dino.jpg", :alt => "Professional") %>

</div>
<div class="span8">
<div class="center hero-unit">
	<h1>I Didn't Ask for This</h1>
 <p>
            <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
        </p>
</div>	
</div>